var fonts = document.createElement('link');
fonts.rel = 'stylesheet';
fonts.href = 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Nunito:wght@700&family=Patrick+Hand&family=Quicksand:wght@700&display=swap';
var theme = document.createElement('link');
theme.rel = 'stylesheet';
theme.href = 'https://talktale.web.app/theme.css';
var icons = document.createElement('link');
icons.rel = 'stylesheet';
icons.href = 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200';
document.body.appendChild(fonts);
